#!/usr/bin/env coot
# python script for coot - generated by dimple
set_nomenclature_errors_on_read("ignore")
molecule = read_pdb("/gpfs/offline1/staff/biomax/domfas/pipeline/alf_output/1408159/7QRZ/dimpleMR/final.pdb")
set_rotation_centre(-7.69, 23.47, -30.96)
set_zoom(30.)
set_view_quaternion(-0.857271, 0.33527, 0, 0.390744)
refl = "/gpfs/offline1/staff/biomax/domfas/pipeline/alf_output/1408159/7QRZ/dimpleMR/final.mtz"
map21 = make_and_draw_map(refl, "FWT", "PHWT", "", 0, 0)
map11 = make_and_draw_map(refl, "DELFWT", "PHDELWT", "", 0, 1)
